version: 2.1
jobs:
  deploy:
    working_directory: /home/circleci/app
    docker:
    - image: circleci/python:3.7-buster-node  ## Use an image that comes with the environment we want to run the script with. 
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install modules
        command: |
          sudo apt-get update
          sudo pip3 install awscli --upgrade
    - run:
        name: Set folder permissions          ## may not be necessary but adding just in case
        command: |
          chown -R circleci:circleci ${CIRCLE_WORKING_DIRECTORY}
          chmod -R 755 ${CIRCLE_WORKING_DIRECTORY}
    - run:
        name: Configure AWS Access Key ID
        command: |
          aws configure set aws_access_key_id \
          $AWS_ACCESS_KEY_ID \
          --profile default
    - run:
        name: Configure AWS Secret Access Key
        command: |
          aws configure set aws_secret_access_key \
          $AWS_SECRET_ACCESS_KEY \
          --profile default
    - run:
        name: Configure AWS default region
        command: |
          aws configure set region $AWS_REGION \
          --profile default
    - deploy: 
        name: Run script to zip files and deploy them to S3
        command: |
          cd ${CIRCLE_WORKING_DIRECTORY}/src
          for folder in */; do zip -r "${folder%/}.zip" "$folder" ; done
          mkdir zipped
          mv *.zip zipped
          aws s3 sync zipped/ s3://slack-bot-commands --delete
          echo "Deployed"
workflows:
  version: 2
  deploy:
    jobs:
    - deploy:
        filters:                              ## ensures only runs script when new commits sent to master
          branches:
            only:
            - master
            